apiVersion: v1
kind: Pod
metadata:
    name: part-inventory-service-pod
    labels:
        app: part-inventory-service
spec:
  containers:
   - name: part-inventory-service
     image: ram1uj/part-inventory-service:latest
     ports:
      - containerPort: 8080
     imagePullPolicy: Never