{{- if .Values.mysql.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inv-order-app.mysqlSecretName" . }}
  labels:
    {{- include "inv-order-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  mysql-user: {{ .Values.mysql.secret.user | quote }}
  mysql-password: {{ .Values.mysql.secret.password | quote }}
{{- end }}
