{{- if and .Values.partOrder.enabled .Values.partOrder.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: part-order-service
  labels:
    {{- include "inv-order-app.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: part-order-service
  minReplicas: {{ .Values.partOrder.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.partOrder.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.partOrder.autoscaling.cpu.enabled }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.partOrder.autoscaling.cpu.averageUtilization }}
    {{- end }}
    {{- if .Values.partOrder.autoscaling.memory.enabled }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.partOrder.autoscaling.memory.averageUtilization }}
    {{- end }}
{{- end }}
